# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'youtube' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
pod "YoutubePlayer-in-WKWebView", "~> 0.2.0" 
  # Pods for youtube

  target 'youtubeTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'youtubeUITests' do
    # Pods for testing
  end

end
